name: Deploy Subscription-cut to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Remove non-deploy files
        run: rm -rf .git .github

      - name: Deploy Subscription-cut
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.hostinger_host }}
          username: ${{ secrets.hostinger_username }}
          password: ${{ secrets.name_password }}
          port: ${{ secrets.hostinger_port }}
          source: "."
          target: "domains/builtbylt.com/public_html/subscription-cut"
          overwrite: true
          rm: false
